@startuml
title RDCU:  Veux comparer les temps de trajet
skinparam Style strictuml
actor "user:user" as ctrl
participant "Ipublic:ServiceTrajet" as Ipublic
note left of Ipublic:**CU01** - Veux comparer les temps de trajet.
ctrl -> Ipublic: liste:get(https://portainer.10.194.33.156.nip.io/components/schemas/TrajetArray) 
Ipublic -> ctrl: liste: tableau du temps de déplacement


@endumlS