@startuml
title: RDCU: service discovery
skinparam Style strictuml

participant "ms:MS_Authentification" as ctrl
participant "Ipublic:ServiceDiscovery" as Ipublic

note left of Ipublic: **CU05** - Avoir une intercommunication entre microservices à l’aide d’une source unique de découverte de route.

ctrl -> Ipublic: reponse = Post(https://localhost/v1/components/schemas/Registration)
Ipublic -> ctrl: reponse = 200

ctrl -> Ipublic: msRoute = get(https://localhost/v1/components/schemas/route)
Ipublic -> ctrl: msRoute = "route"

@enduml