@startuml
title Diagramme de contexte C&C
skinparam component {
  backgroundColor<<Interne>> DarkKhaki
  backgroundColor<<Exterme>> Green
}
actor User as u
 [Authentification_MS] as ms <<Interne>>
 [Chaos]  as ko <<Interne>> 
 [Database] as bd <<Interne>>
 () IPublic as i <<Exterme>>
 note bottom of i:IPublic est interface des microservices discovey, trajet et monitoring

u   -right->  ms
ms   -down->  i 
ms   ->  bd 
ko -up->  ms
@enduml
